### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by PranavPurwar** [Sketchware-Pro/website#9]
Yes, this repository is definitely maintained by @NiceSapien and not by official Sketchware Pro maintainers. Why is it hosted in the organisation account then? No un-official docs here, please. Even the README is misleading to consider it as "official". 
![Screenshot_2022-09-30-21-28-35](https://user-images.githubusercontent.com/75154889/193310559-6a086e79-ab03-4528-98ee-814e2bcbf9e0.png)

**Comment by NiceSapien** [comment]
Do you know:
(Take Discord as example) They don't have just one team. They have multiple teams for different systems. Not the developers of android version will also develop the web version. They're different, but still "official".

**Comment by PranavPurwar** [comment]
You're not a part of their team* And this isn't official*

**Comment by nicesapien-too** [comment]
Ok

**Comment by PranavPurwar** [comment]
reopen

**Comment by PranavPurwar** [comment]
I would respectfully ask you to reopen this issue else your mom
